export interface TranslationMap {
  [key: string]: string;
}

export const translations: Record<string, TranslationMap> = {
  en: {
    nav_home: 'Home',
    nav_profile: 'Profile',
    nav_settings: 'Settings',
    nav_subscription: 'Subscription',
    nav_courses: 'Courses',
    nav_practice: 'Practice',
    nav_notes: 'Lecture Notes',
    nav_editor: 'Editor',
    nav_chatbot: 'Chatbot',
    nav_chat: 'Chat',
    nav_notifications: 'Notifications',
    nav_games: 'Games',
    nav_lounge: 'Study Lounge',
    nav_admin: 'Admin',
    nav_dashboard: 'Dashboard',
    sb_section_workspace: 'Workspace',
    sb_section_activity: 'Activity',
    sb_section_account: 'Account',
    sb_loading: 'Loading…',
    sb_night: 'Night',
    tb_back: '← Back',
    tb_menu_aria: 'Open menu',
    tb_study: 'Study',
    tb_study_title: 'Study Techniques',
    tb_focus_mini: 'Focus',
    tb_pause_title: 'Pause',
    tb_stop_title: 'Stop',
    tb_resume_title: 'Resume',
    st_rhythm: 'Study rhythm',
    st_focus_title: 'Focus Session',
    st_focus_sub: 'Set your timing and ambience before you start studying.',
    st_close_aria: 'Close',
    st_pomodoro_desc: 'Classic focus rhythm · 25 / 5',
    st_5217_desc: 'Longer deep-work block',
    st_9020_desc: 'Extended study sprint',
    st_custom_desc: 'Use your own intervals',
    st_focus_min: 'Focus (min)',
    st_short_break_min: 'Short break (min)',
    st_long_break_min: 'Long break (min)',
    st_cycles_before_long: 'Cycles before long break',
    st_ambience: 'Ambience',
    st_music_none: 'None',
    st_music_hint_lofi: 'Quiet Focus playlist · always available',
    st_music_hint_lofi_radio: 'Lofi Girl radio · always available',
    st_music_hint_youtube: 'Choose a saved playlist below',
    st_music_hint_spotify: 'Controls your Spotify playback',
    st_music_hint_none: 'No music during session',
    st_short_break: 'Short break',
    st_long_break: 'Long break',
    st_default_saved: 'Default focus session saved',
    st_start_focus: '▶ Start focus session',
    st_save_default: 'Save as default',
    welcome_title: 'Select a file to read',
    welcome_sub: 'Open a subject in the sidebar and click any file — it loads here as a real document.',
    welcome_hint: '💡 Select any text or formula → AI automatically asks if you need help',
    settings_title: '⚙️ Settings',
    settings_subtitle: 'Customise your experience',
    settings_music_section: '🎵 Music Services',
    settings_music_desc: 'Connect a music service to play your own playlists during study sessions.',
    settings_spotify_not_connected: 'Not connected',
    settings_spotify_connect: 'Connect',
    settings_spotify_disconnect: 'Disconnect',
    settings_spotify_prev: 'Previous',
    settings_spotify_play: 'Play/Pause',
    settings_spotify_next: 'Next',
    settings_yt_title: 'YouTube Playlists',
    settings_yt_status: 'No playlists saved',
    settings_yt_name_ph: 'Name (e.g. Lofi Study)',
    settings_yt_url_ph: 'YouTube playlist URL',
    settings_yt_add: 'Add',
    settings_delete_account: 'Delete account',
    settings_delete_account_lbl: 'Delete account',
    settings_delete_account_desc: 'Permanently deletes your account and all data. This cannot be undone.',
    settings_clear_confirm: 'Clear all AI chat history? This cannot be undone.',
    settings_delete_modal_title: 'Delete your account?',
    settings_delete_modal_desc: 'This will permanently delete your account and all associated data including notes, settings, and chat history. <strong style="color:rgba(239,68,68,.8)">This cannot be undone.</strong>',
    settings_delete_modal_cancel: 'Cancel',
    settings_delete_modal_confirm: 'Yes, delete',
    profile_title: '👤 Profile',
    profile_subtitle: 'Manage your account information',
    profile_hero_title: 'Profile',
    profile_personal_details: 'Personal details',
    profile_ph_name: 'Your name',
    profile_ph_email: 'Email',
    profile_ph_university: 'University',
    profile_ph_programme: 'Programme',
    profile_label_vert: 'Vertiefung (Fachprofil)',
    profile_ph_vert: 'e.g. Mechatronik',
    profile_label_matrikel_no: 'Matrikel No.',
    profile_ph_matrikel: 'Matrikel no.',
    profile_german_test: 'German Test',
    profile_ph_german_test: 'e.g. TestDaF',
    profile_target_level: 'Target Level',
    profile_select_level: 'Select your level…',
    fc_generate: '✨ Generate cards',
    fc_search_ph: 'Search flashcards…',
    fc_sort_aria: 'Sort decks',
    fc_sort_recent: 'Recently studied',
    fc_sort_name: 'By name',
    fc_sort_size: 'By card count',
    fc_sort_created: 'Recently created',
    fc_view_mode_aria: 'View mode',
    fc_grid_view_aria: 'Grid view',
    fc_list_view_aria: 'List view',
    fc_loading: 'Loading decks…',
    fc_view_all: 'View all decks',
    fc_select_deck: 'Select a deck',
    fc_zero_cards: '0 cards',
    fc_study_settings: '⚙ Study settings',
    fc_pick_deck: 'Pick a deck to start studying.',
    fc_previous: '◀ Previous',
    fc_flip: '↻ Flip card',
    fc_next: 'Next ▶',
    qz_generate: '✨ Generate quiz',
    qz_search_ph: 'Search quizzes…',
    qz_sort_aria: 'Sort quizzes',
    qz_sort_recent: 'Recently taken',
    qz_sort_name: 'By name',
    qz_sort_score: 'By best score',
    qz_sort_created: 'Recently created',
    qz_view_mode_aria: 'View mode',
    qz_grid_view_aria: 'Grid view',
    qz_list_view_aria: 'List view',
    qz_loading: 'Loading quizzes…',
    qz_view_all: 'View all quizzes',
    qz_select_quiz: 'Select a quiz',
    qz_zero_questions: '0 questions',
    qz_settings: '⚙ Quiz settings',
    qz_pick_quiz: 'Pick a quiz to start.',
    qz_previous: '◀ Previous',
    qz_submit: 'Submit',
    qz_next: 'Next ▶',
    wc_card_title: 'Deutsch Writing Coach',
    wc_card_sub: 'German Writing Coach · write a paragraph, get AI feedback adapted to your level',
    wc_back: '← Back',
    wc_view_sub: 'Write a German paragraph and get AI feedback adapted to your level.',
    wc_no_level_title: 'Set your German level in Profile first',
    wc_no_level_sub: 'The writing coach grades your text against the level on your profile. Open Profile, set your level (e.g. B2 or C1 Hochschule), then come back here.',
    wc_go_profile: 'Go to Profile',
    wc_feedback_level: 'Feedback level',
    wc_level_title: 'Edit your level in Profile',
    wc_level_source: 'Imported from Profile',
    wc_text_type: 'Text type',
    wc_input_ph: 'Write your German paragraph here…',
    wc_analyze: 'Analyze with AI',
    wc_analyzing: 'Analyzing…',
    gl_hero_eyebrow: 'Language practice hub',
    gl_title: 'Deutsch lernen',
    gl_sub: 'Practice reading, listening, writing, speaking, vocabulary, and grammar in one focused preparation workspace.',
    gl_avg_progress: 'avg progress',
    gl_this_week: 'this week',
    gl_ai_writing_coach: 'AI writing coach',
    gl_imported_profile: 'Imported from your profile',
    gl_start_practice: 'Start practice',
    gl_reading_aria: 'Open Leseverstehen practice',
    gl_reading_sub: 'Reading comprehension',
    gl_listening_aria: 'Open Hörverstehen practice',
    gl_listening_sub: 'Listening comprehension',
    gl_writing_aria: 'Open Schreiben practice',
    gl_writing_sub: 'Writing tasks',
    gl_ai_feedback: 'AI feedback',
    gl_speaking_aria: 'Open Sprechen practice',
    gl_speaking_sub: 'Speaking exercises',
    gl_practice_mode: 'Practice mode',
    gl_vocab_aria: 'Open Wortschatz practice',
    gl_vocab_sub: 'Vocabulary builder',
    gl_grammar_aria: 'Open Grammatik practice',
    gl_grammar_sub: 'Grammar practice',
    gl_practice_progress: 'Practice progress',
    gl_open_practice: 'Open practice',
    sub_title: '⭐ Subscription',
    sub_subtitle: 'Try Pro free for 7 days, then €11.99/month',
    sub_badge_popular: '🔥 Most popular',
    sub_plan_name: 'Pro',
    sub_trial_badge: '7-day free trial',
    sub_price_suffix: '/ month after trial',
    sub_feat_ai: 'Generous AI usage (fair-use: 2000 chat · 200 generations / month)',
    sub_feat_pdf: 'PDF reader',
    sub_feat_notes: 'Unlimited lecture notes',
    sub_feat_multi: 'Multi-PDF summaries',
    sub_feat_support: 'Priority support',
    sub_feat_chat: 'Chat rooms',
    sub_active: '✓ Active subscription',
    sub_manage: '⚙️ Manage / Cancel subscription',
    sub_cancel_note: 'Cancel anytime. No charge during trial.',
    sub_usage_chat: 'Chat & tutor this month',
    sub_usage_gen: 'Quiz / flashcard / notes generations',
    sub_pay_with: 'Pay with',
    sub_pay_card: '💳 Card',
    sub_start_trial: 'Start free 7-day trial',
    sub_subscribe: 'Subscribe — €11.99/month',
    sub_upgrade: 'Upgrade to Pro',
    sub_pro_activated: 'Pro activated!',
    sub_pro_enjoy: 'Enjoy unlimited access.',
    sub_payment_received: 'Payment received',
    sub_activating: 'Activating your Pro plan...',
    sub_activation_error: 'Activation error',
    sub_activation_error_sub: 'Contact support.',
    sub_paypal_error: 'PayPal error',
    sub_paypal_error_default: 'Please try again or use card.',
    sub_payment_unavailable: 'Payment unavailable',
    sub_payment_unavailable_sub: 'Subscription configuration is missing.',
    sub_payment_success: 'Payment successful!',
    pw_welcome: 'Welcome to Minallo',
    pw_desc: 'To access all features, start your free 7-day trial. No charge until the trial ends.',
    pw_desc_trialed: 'Subscribe to access all Minallo features for €11.99/month.',
    pw_trial_badge: '✨ 7-day free trial',
    pw_after_trial: '/ month after trial',
    pw_feat_ai: 'Generous AI usage (fair-use: 2000 chat · 200 generations / month)',
    pw_feat_pdf: 'PDF reader & lecture notes',
    pw_feat_multi: 'Multi-PDF summaries',
    pw_feat_chat: 'Chat rooms',
    pw_feat_support: 'Priority support',
    pw_cancel_note: 'Cancel anytime. No charge during trial.',
    pw_pay_methods: 'Pay with Card · Klarna · PayPal',
    pw_signout: 'Sign out',
    dash_empty_title: 'Your dashboard is empty',
    dash_empty_sub_pre: 'Click ',
    dash_empty_sub_post: ' to add widgets',
    wp_title: '✶ Add Widgets',
    dash_no_courses: 'No courses yet — add some in Subjects',
    dash_no_courses_short: 'No courses yet',
    gcw_connect_btn: 'Connect Google Calendar',
    gcw_connect_sub: 'Sign in with Google to view and edit your events',
    mastery_take_quiz: 'Take a quiz to see your mastery for this course.',
    wdg_courses_name: 'Course Shortcuts',
    wdg_courses_desc: 'Jump into any course',
    wdg_mail_name: 'New Mails',
    wdg_mail_desc: 'Unread messages only',
    wdg_notes_name: 'Quick Notes',
    wdg_notes_desc: 'Personal scratch pad',
    wdg_stats_name: 'Study Stats',
    wdg_stats_desc: 'Weekly progress',
    wdg_deadlines_name: 'Deadlines',
    wdg_deadlines_desc: 'Upcoming due dates',
    wdg_weather_name: 'Campus Weather',
    wdg_weather_desc: 'Braunschweig forecast',
    wdg_ai_name: 'AI Quick Chat',
    wdg_ai_desc: 'Ask anything instantly',
    wdg_gcal_name: 'Google Calendar',
    wdg_gcal_desc: 'View & edit your events',
    wdg_mastery_name: 'Practice focus',
    wdg_mastery_desc: 'Topics to strengthen from your quizzes',
    auth_email_label: 'Email',
    auth_password_label: 'Password',
    auth_confirm_label: 'Confirm Password',
    auth_title_signin: 'Sign in to your account',
    auth_title_signup: 'Create your account',
    auth_submit_signin: 'Sign In',
    auth_submit_signup: 'Create Account',
    auth_google_btn: 'Continue with Google',
    auth_stay: 'Stay signed in',
    auth_stay_timeout: '(30 min timeout)',
    auth_switch_signin: "Don't have an account? Sign up",
    auth_switch_signup: 'Already have an account? Sign in',
    auth_brand_tagline: 'Study smarter',
    auth_badge_signin: 'Welcome back',
    auth_badge_signup: 'Welcome to Minallo',
    auth_heading_signin: 'Sign in to your study space.',
    auth_heading_signup: 'Create your Minallo account.',
    auth_body_signin: 'Continue your courses, German practice, PDF work, playlists, games, and focus sessions from one calm dashboard.',
    auth_body_signup: 'Start organizing your study life with AI help, PDF tools, German practice, focus sessions, playlists, and study games.',
    auth_pw_toggle_aria: 'Show or hide password',
    auth_pw_toggle_title: 'Show/hide password',
    auth_email_ph: 'your@email.com',
    auth_forgot: 'Forgot password?',
    auth_or: 'or',
    auth_google_signup_btn: 'Sign up with Google',
    auth_switch_prefix_signin: "Don't have an account?",
    auth_switch_prefix_signup: 'Already have an account?',
    auth_switch_link_signup: 'Sign up',
    auth_switch_link_signin: 'Sign in',
    auth_submit_signin_short: 'Sign in',
    auth_submit_signup_short: 'Create account',
    auth_buddy_pill: '24/7 study companion',
    auth_buddy_title: 'Your Minallo study buddy',
    auth_buddy_body: 'Ask questions, organize your work, practice German, and stay focused without switching tools.',
    auth_mini_ai_title: 'AI Tutor',
    auth_mini_ai_desc: 'Course-aware help with citations.',
    auth_mini_pdf_title: 'PDF Workspace',
    auth_mini_pdf_desc: 'Read, edit, and organize notes.',
    auth_mini_focus_title: 'Focus Mode',
    auth_mini_focus_desc: 'Pomodoro sessions and streaks.',
    auth_mini_de_title: 'German Practice',
    auth_mini_de_desc: 'Vocabulary, grammar, and examples.',
    auth_pw_match: 'Passwords match',
    auth_pw_no_match: 'Passwords do not match',
    auth_please_wait: 'Please wait...',
    ob_step1: "Let's set up your profile — step 1 of 3",
    ob_step2: 'Tell us about yourself — step 2 of 3',
    ob_step3: 'Details — step 3 of 3',
    ob_welcome_title: 'Welcome to Minallo!',
    ob_path_title: 'Your path',
    ob_almost_there: 'Almost there!',
    ob_de_journey: 'Your German journey',
    ob_log_out: 'Log out',
    ob_first_name: 'First name',
    ob_last_name: 'Last name',
    ob_age: 'Age',
    ob_email: 'Email',
    ob_first_name_ph: 'e.g. Mohamed',
    ob_last_name_ph: 'e.g. Al-Rashid',
    ob_age_ph: 'e.g. 21',
    ob_email_ph: 'e.g. your@email.com',
    ob_programme: 'Study programme',
    ob_programme_ph: 'e.g. Maschinenbau',
    ob_semester: 'Semester',
    ob_semester_ph: 'e.g. 3',
    ob_matrikel: 'Matrikelnummer',
    ob_matrikel_ph: 'e.g. 2456789',
    ob_continue_btn: 'Continue',
    ob_back_btn: '← Back',
    ob_finish_btn: 'Finish',
    ob_saving: '⏳ Saving…',
    ob_prompt_describe: 'Which best describes you?',
    ob_path_uni: 'University student',
    ob_path_uni_sub: 'Already enrolled at a German university',
    ob_path_learner: 'German learner',
    ob_path_learner_sub: 'Preparing for a language test to enroll',
    ob_bundesland: 'Bundesland',
    ob_bundesland_ph: 'Select your Bundesland…',
    ob_university: 'University',
    ob_uni_ph_before: 'Pick a Bundesland first',
    ob_uni_ph_after: 'e.g. TU Braunschweig',
    ob_vertiefung: 'Vertiefung (Fachprofil)',
    ob_vertiefung_ph: 'e.g. Mechatronik',
    ob_vertiefung_optional_ph: 'Type your specialization (optional)',
    ob_which_test: 'Which test are you preparing for?',
    ob_test_telc_sub: 'The European Language Certificates',
    ob_test_goethe_sub: 'Goethe-Institut language certificate',
    ob_level_question: 'What is your current / target level?',
    ob_err_fill_all: 'Please fill in all fields',
    ob_err_valid_email: 'Please enter a valid email',
    ob_err_bundesland: 'Please select your Bundesland',
    ob_err_pick_uni: 'Please pick a university from the list',
    ob_err_select_test: 'Please select a test',
    ob_err_select_level: 'Please select your level',
    ob_save_failed_prefix: 'Save failed: ',
    auth_pw_weak: 'Weak',
    auth_pw_fair: 'Fair',
    auth_pw_good: 'Good',
    auth_pw_strong: 'Strong',
    auth_user_fallback: 'User',
    auth_confirm_signout: 'Sign out of Minallo?',
    settings_save_btn: 'Save Changes',
    card_studip_desc: 'Courses & materials',
    card_mail_desc: 'Outlook Web Access',
    card_connect_desc: 'Exams & grades',
    card_timetable_name: 'Timetable',
    card_timetable_desc: 'Semester schedule',
    card_cert_name: 'Certificates',
    card_cert_desc: 'Enrolment docs',
    profile_label_name: 'Full name',
    profile_label_email: 'Email',
    profile_label_university: 'University',
    profile_label_programme: 'Study programme',
    profile_label_matrikel: 'Matrikel number',
    profile_save_btn: '💾 Save changes',
    settings_appearance: 'Appearance',
    settings_dark_mode: 'Dark mode',
    settings_language: 'Language',
    settings_ai_section: 'AI Assistant',
    settings_auto_open: 'Auto-open on text select',
    settings_save_chat: 'Save chat history per PDF',
    settings_notifications: 'Notifications',
    settings_sync_alerts: 'Lecture note sync alerts',
    settings_mail_alerts: 'New mail alerts',
    settings_data: 'Data',
    settings_clear_chat: 'Clear all AI chat history',
    settings_clear_btn: 'Clear history',
    settings_account: 'Account',
    settings_signout: 'Sign out of Minallo',
    settings_logout_btn: 'Log out',
    ln_title: '🎬 Lecture Notes',
    ln_sync_btn: 'Sync from Extension',
    sb_subjects: '📚 Subjects',
    sb_timetable: '🗓️ Timetable',
    sb_mails: '✉️ Mails',
    sb_back: '← All subjects',
    back_btn: '← Back',
    pdf_fit: 'Fit',
    pdf_single: 'Single page',
    pdf_download: '⬇ Download',
    ai_ready: 'Ready to help',
    chip_summarise: '✨ Summarise',
    chip_formulas: '🔢 Formulas',
    chip_quiz: '📝 Quiz me',
    chip_keyideas: '💡 Key ideas',
    chip_analogy: '🔗 Analogy',
    depth_label: 'Depth:',
    chip_brief: 'Brief',
    chip_standard: 'Standard',
    chip_thorough: 'In-depth',
    level_label: 'Level:',
    chip_easy: 'Easy',
    chip_medium: 'Medium',
    chip_hard: 'Hard',
    stop_btn: '⏹ Stop generating',
    ai_placeholder: 'Ask anything about this document…',
    ai_welcome: "Hey! 👋 Open a PDF, select any text or formula and I'll help you understand it!",
    ai_tip_no_pdf: '💡 Tip: open a PDF first so I can answer from the actual document!',
    ai_file_loaded_post:
      "loaded! Ask me anything about it — I'll answer based on the document content. 🎓",
    ai_chat_cleared_msg: 'Chat cleared! What would you like to know? 😊',
    chat_restored: '— chat history restored —',
    no_file_open: 'No file open',
    loading_pdf: 'Loading PDF…',
    not_in_demo: 'This file is not available in the demo.',
    not_in_demo_multi: 'not available in demo',
    download_failed: 'Download failed.',
    copy_btn: 'Copy',
    you_label: 'You',
    nothing_yet: 'Nothing here yet',
    studip_subtitle: 'TU Braunschweig · Your courses & materials',
    studip_back: '← Portal',
    sd_subjects: '📚 Subjects',
    sd_timetable: '🗓️ Timetable',
    sd_mails: '✉️ Mails',
    sel_explain: 'Explain this',
    sel_formula: 'Break down formula',
    sel_dismiss: 'Dismiss',
    sel_preview: '📌 You selected:',
    sync_syncing: 'Syncing…',
    sync_synced: 'Synced ✓',
    sync_no_ext: 'Extension not detected',
    toast_saved: '💾 Saved to Lecture Notes',
    toast_new_summary_pre: '📝 New summary: ',
    toast_tap_view: 'Tap View to open your lecture notes',
    toast_synced_s: 'note synced',
    toast_synced_p: 'notes synced',
    toast_no_notes: '⚠️ No notes found',
    toast_summarize_first: 'Summarize a lecture in the extension first',
    toast_sign_in: '⚠️ Sign in to save',
    toast_profile_saved: '✅ Profile saved',
    toast_profile_saved_sub: 'Saved to your account',
    toast_save_failed: '❌ Save failed',
    toast_chat_cleared: '🗑️ Chat history cleared',
    toast_chat_cleared_sub: 'All saved chats have been removed',
    toast_settings_saved: '✅ Settings saved',
    toast_settings_saved_sub: 'Your preferences have been updated',
    toast_signed_out: '👋 Signed out',
    toast_signed_out_sub: 'See you next time!',
    toast_coming_soon: '🚀 Coming soon',
    toast_coming_soon_sub: 'Payment integration coming soon!',
    toast_inactivity: '⏰ Signed out due to inactivity',
    toast_inactivity_sub: 'Sign in again to continue',
    err_connection: 'Connection error — please refresh the page',
    err_fill_fields: 'Please fill in all fields',
    err_confirm_pw: 'Please confirm your password',
    err_pw_mismatch: 'Passwords do not match',
    err_pw_length: 'Password must be at least 8 characters',
    err_account_created:
      '✅ Account created! Check your email and click the confirmation link to get started.',
    err_confirm_email: '⚠️ Please confirm your email first — check your inbox for the link.',
    err_wrong_pw:
      '⚠️ Incorrect password — or did you sign up with Google? Try the Google button below, or use the link to create a new account.',
    err_network: 'Network error — check your connection.',
    aip_new_chat: 'New chat',
    aip_chats_label: 'Chats',
    aip_no_chats: 'No chats yet',
    aip_subtitle: 'Where should we start?',
    aip_landing_ph: 'Ask me anything…',
    aip_followup_ph: 'Ask a follow-up…',
    aip_upload_btn: 'Upload photos & files',
    set_unsaved: 'Unsaved changes',
    set_saving: 'Saving…',
    set_saved: 'Saved ✓',
    set_save_failed: 'Save failed',
    set_deleting: 'Deleting...',
    set_yes_delete: 'Yes, delete',
    sub_loading: 'Loading...',
    sub_redirecting: 'Redirecting...',
    sub_not_available: 'Not available',
    sub_no_stripe: 'No Stripe account found.',
    sub_error: 'Error',
    sub_portal_failed: 'Could not open portal.',
    sub_signin_required: 'Sign in required',
    sub_login_first: 'Please log in first.',
    sub_checkout_failed: 'Could not start checkout.',
    cb_header_title: 'Chatbot',
    cb_header_subtitle: 'Course-aware AI tutor',
    cb_open_panel: 'Open context panel',
    cb_close_panel: 'Close context panel',
    cb_sidebar_eyebrow: 'Minallo',
    cb_sidebar_title: 'AI Chats',
    cb_collapse_sidebar: 'Collapse sidebar',
    cb_new_chat: 'New chat',
    cb_search_chats: 'Search chats...',
    cb_search_chats_aria: 'Search chats',
    cb_safe_title: 'Course-safe mode',
    cb_safe_text: 'Answers can be restricted to uploaded lectures, exercises, and course files.',
    cb_current_chat: 'Current chat',
    cb_chat_title_new: 'New chat',
    cb_context_active: 'Course context active',
    cb_empty_title: 'What are we studying today?',
    cb_empty_subtitle: 'Upload a lecture, import a course file, solve an exercise, create notes, or ask Minallo to explain the topic like a personal tutor.',
    cb_greet_ready: 'ready to study smarter?',
    cb_tutor_solve: 'Solve with me',
    cb_tutor_solve_title: 'Socratic — guides you step by step instead of revealing the full answer',
    cb_tutor_explain: 'Explain',
    cb_tutor_explain_title: 'Direct explanation grounded in your course files',
    cb_tutor_quiz: 'Quiz me',
    cb_tutor_quiz_title: 'Generates a short MCQ check on this topic from your course files',
    cb_tutor_group_aria: 'Tutor mode',
    cb_upload_btn: 'Upload photos & files',
    cb_import_btn: 'Import from Course',
    cb_input_placeholder: 'Ask anything about your lectures, exercises, or course files...',
    cb_input_aria: 'Type your message',
    cb_send_btn: 'Send message',
    cb_action_summarize_title: 'Summarize lecture',
    cb_action_summarize_desc: 'Turn PDFs into clean notes',
    cb_action_solve_title: 'Solve exercise',
    cb_action_solve_desc: 'Step-by-step with formulas',
    cb_action_exam_title: 'Exam answer',
    cb_action_exam_desc: 'Short, structured, precise',
    cb_action_flash_title: 'Create flashcards',
    cb_action_flash_desc: 'Save key concepts fast',
    cb_ctx_eyebrow: 'Context',
    cb_ctx_title: 'Study panel',
    cb_tab_files: 'Files',
    cb_tab_sources: 'Sources',
    cb_tab_notes: 'Notes',
    cb_notes_card_title: 'Saved replies',
    cb_notes_empty: 'Save useful AI replies here by tapping the Save to notes button under any reply.',
    cb_sources_card_title: 'Sources used',
    cb_sources_count_zero: '0 files',
    cb_tools_title: 'AI tools',
    cb_tool_quiz: 'Quiz me',
    cb_tool_flashcards: 'Flashcards',
    cb_tool_summary: 'Summary',
    cb_tool_export: 'Export',
    cb_streak_title: 'Study streak',
    cb_streak_text: 'You are one focused session away from keeping today’s streak alive.',
    cb_modal_eyebrow: 'Course files',
    cb_modal_title: 'Import from Course',
    cb_modal_close: 'Close',
    cb_modal_course_aria: 'Course',
    cb_modal_search_ph: 'Search folders or files...',
    cb_modal_search_aria: 'Search folders or files',
    cb_modal_back: 'Back',
    cb_modal_hint_title: 'Smart import',
    cb_modal_hint_text: 'Imported course files are attached to this chat context and can be used for citations, summaries, and exercise solving.',
    cb_modal_folder_selected: 'folder selected',
    cb_modal_folders_selected: 'folders selected',
    cb_modal_cancel: 'Cancel',
    cb_modal_import: 'Import',
    cb_response_stopped: 'Response stopped.',
    cb_request_failed: 'Request failed.',
    cb_no_response: 'No response.',
    cb_error_prefix: '❌ Error: ',
    cb_verified: '✓ Verified',
    cb_partially_verified: '⚠ Partially verified',
    cb_missing_context: '⚠ Missing context',
    cb_sources_summary: 'Sources',
    cb_sender_minallo: 'Minallo AI',
    cb_answered_using_context: 'Answered using course context',
    cb_stop_response_aria: 'Stop AI response',
    cb_pasted_screenshot: 'Pasted screenshot',
    cb_act_copy: 'Copy',
    cb_act_regen: 'Regenerate',
    cb_act_bookmark: 'Bookmark',
    cb_act_bookmark_title: 'Bookmark this reply',
    cb_act_thumb_up: 'Thumbs up',
    cb_act_thumb_down: 'Thumbs down',
    cb_act_copied: 'Copied',
    cb_act_saved: 'Saved',
    cb_act_already_saved: 'Already saved',
    cb_act_busy: 'Busy',
    cb_act_nothing_export: 'Nothing to export',
    cb_act_exported: 'Exported',
    cb_untitled_course: 'Untitled course',
    cb_open_course_first: 'Open a course on Minallo first to import its files here.',
    cb_no_files_in_folder: 'No files in this folder.',
    cb_no_matches: 'No matches.',
    cb_no_files_in_course: 'No files in this course.',
    cb_importing: 'Importing…',
    cb_remove_saved_reply: 'Remove saved reply',
    cb_section_pinned: 'Pinned',
    cb_section_recent: 'Recent',
    cb_clear_all: 'Clear all chats',
    cb_clear_all_confirm: "Delete every chat in the sidebar? This can't be undone.",
    cb_storage_full_title: 'Chat storage full',
    cb_storage_full_text: 'Browser storage is full. Delete some chats to keep new ones from being lost on reload.',
    cb_storage_blocked_title: 'Chats not saved',
    cb_storage_blocked_text: 'Your browser blocked storage (private mode?). Chats will not persist across reloads.',
    cb_menu_pin: 'Pin',
    cb_menu_unpin: 'Unpin',
    cb_menu_rename: 'Rename',
    cb_menu_delete: 'Delete',
    cb_rename_chat_aria: 'Rename chat',
    cb_empty_draft: 'Empty draft',
  },
  de: {
    nav_home: 'Startseite',
    nav_profile: 'Profil',
    nav_settings: 'Einstellungen',
    nav_subscription: 'Abonnement',
    nav_courses: 'Kurse',
    nav_practice: 'Üben',
    nav_notes: 'Vorlesungsnotizen',
    nav_editor: 'Editor',
    nav_chatbot: 'Chatbot',
    nav_chat: 'Chat',
    nav_notifications: 'Benachrichtigungen',
    nav_games: 'Spiele',
    nav_lounge: 'Lernlounge',
    nav_admin: 'Admin',
    nav_dashboard: 'Übersicht',
    sb_section_workspace: 'Arbeitsbereich',
    sb_section_activity: 'Aktivität',
    sb_section_account: 'Konto',
    sb_loading: 'Lädt…',
    sb_night: 'Nacht',
    tb_back: '← Zurück',
    tb_menu_aria: 'Menü öffnen',
    tb_study: 'Lernen',
    tb_study_title: 'Lerntechniken',
    tb_focus_mini: 'Fokus',
    tb_pause_title: 'Pause',
    tb_stop_title: 'Stopp',
    tb_resume_title: 'Fortsetzen',
    st_rhythm: 'Lernrhythmus',
    st_focus_title: 'Fokus-Session',
    st_focus_sub: 'Lege Timing und Atmosphäre fest, bevor du mit dem Lernen beginnst.',
    st_close_aria: 'Schließen',
    st_pomodoro_desc: 'Klassischer Fokusrhythmus · 25 / 5',
    st_5217_desc: 'Längerer Deep-Work-Block',
    st_9020_desc: 'Ausgedehnter Lernsprint',
    st_custom_desc: 'Eigene Intervalle verwenden',
    st_focus_min: 'Fokus (Min.)',
    st_short_break_min: 'Kurze Pause (Min.)',
    st_long_break_min: 'Lange Pause (Min.)',
    st_cycles_before_long: 'Zyklen bis zur langen Pause',
    st_ambience: 'Atmosphäre',
    st_music_none: 'Keine',
    st_music_hint_lofi: 'Quiet-Focus-Playlist · immer verfügbar',
    st_music_hint_lofi_radio: 'Lofi-Girl-Radio · immer verfügbar',
    st_music_hint_youtube: 'Wähle unten eine gespeicherte Playlist',
    st_music_hint_spotify: 'Steuert deine Spotify-Wiedergabe',
    st_music_hint_none: 'Keine Musik während der Session',
    st_short_break: 'Kurze Pause',
    st_long_break: 'Lange Pause',
    st_default_saved: 'Standard-Fokus-Session gespeichert',
    st_start_focus: '▶ Fokus-Session starten',
    st_save_default: 'Als Standard speichern',
    welcome_title: 'Wähle eine Datei zum Lesen',
    welcome_sub: 'Öffne ein Fach in der Seitenleiste und klicke auf eine Datei — sie wird hier als echtes Dokument geladen.',
    welcome_hint: '💡 Markiere beliebigen Text oder eine Formel → die KI fragt automatisch, ob du Hilfe brauchst',
    settings_title: '⚙️ Einstellungen',
    settings_subtitle: 'Personalisiere dein Erlebnis',
    settings_music_section: '🎵 Musikdienste',
    settings_music_desc: 'Verbinde einen Musikdienst, um eigene Playlists während Lern-Sessions abzuspielen.',
    settings_spotify_not_connected: 'Nicht verbunden',
    settings_spotify_connect: 'Verbinden',
    settings_spotify_disconnect: 'Trennen',
    settings_spotify_prev: 'Zurück',
    settings_spotify_play: 'Wiedergabe/Pause',
    settings_spotify_next: 'Weiter',
    settings_yt_title: 'YouTube-Playlists',
    settings_yt_status: 'Keine Playlists gespeichert',
    settings_yt_name_ph: 'Name (z. B. Lofi Lernen)',
    settings_yt_url_ph: 'YouTube-Playlist-URL',
    settings_yt_add: 'Hinzufügen',
    settings_delete_account: 'Konto löschen',
    settings_delete_account_lbl: 'Konto löschen',
    settings_delete_account_desc: 'Löscht dein Konto und alle Daten endgültig. Dies kann nicht rückgängig gemacht werden.',
    settings_clear_confirm: 'Den gesamten KI-Chatverlauf löschen? Dies kann nicht rückgängig gemacht werden.',
    settings_delete_modal_title: 'Konto löschen?',
    settings_delete_modal_desc: 'Dadurch werden dein Konto und alle zugehörigen Daten einschließlich Notizen, Einstellungen und Chatverlauf dauerhaft gelöscht. <strong style="color:rgba(239,68,68,.8)">Dies kann nicht rückgängig gemacht werden.</strong>',
    settings_delete_modal_cancel: 'Abbrechen',
    settings_delete_modal_confirm: 'Ja, löschen',
    profile_title: '👤 Profil',
    profile_subtitle: 'Verwalte deine Kontoinformationen',
    profile_hero_title: 'Profil',
    profile_personal_details: 'Persönliche Daten',
    profile_ph_name: 'Dein Name',
    profile_ph_email: 'E-Mail',
    profile_ph_university: 'Universität',
    profile_ph_programme: 'Studiengang',
    profile_label_vert: 'Vertiefung (Fachprofil)',
    profile_ph_vert: 'z. B. Mechatronik',
    profile_label_matrikel_no: 'Matrikelnummer',
    profile_ph_matrikel: 'Matrikelnr.',
    profile_german_test: 'Deutschprüfung',
    profile_ph_german_test: 'z. B. TestDaF',
    profile_target_level: 'Zielniveau',
    profile_select_level: 'Wähle dein Niveau…',
    fc_generate: '✨ Karten generieren',
    fc_search_ph: 'Karteikarten suchen…',
    fc_sort_aria: 'Decks sortieren',
    fc_sort_recent: 'Zuletzt gelernt',
    fc_sort_name: 'Nach Name',
    fc_sort_size: 'Nach Kartenanzahl',
    fc_sort_created: 'Zuletzt erstellt',
    fc_view_mode_aria: 'Ansichtsmodus',
    fc_grid_view_aria: 'Rasteransicht',
    fc_list_view_aria: 'Listenansicht',
    fc_loading: 'Decks werden geladen…',
    fc_view_all: 'Alle Decks anzeigen',
    fc_select_deck: 'Deck auswählen',
    fc_zero_cards: '0 Karten',
    fc_study_settings: '⚙ Lerneinstellungen',
    fc_pick_deck: 'Wähle ein Deck, um mit dem Lernen zu beginnen.',
    fc_previous: '◀ Zurück',
    fc_flip: '↻ Karte umdrehen',
    fc_next: 'Weiter ▶',
    qz_generate: '✨ Quiz generieren',
    qz_search_ph: 'Quizze suchen…',
    qz_sort_aria: 'Quizze sortieren',
    qz_sort_recent: 'Zuletzt bearbeitet',
    qz_sort_name: 'Nach Name',
    qz_sort_score: 'Nach bester Punktzahl',
    qz_sort_created: 'Zuletzt erstellt',
    qz_view_mode_aria: 'Ansichtsmodus',
    qz_grid_view_aria: 'Rasteransicht',
    qz_list_view_aria: 'Listenansicht',
    qz_loading: 'Quizze werden geladen…',
    qz_view_all: 'Alle Quizze anzeigen',
    qz_select_quiz: 'Quiz auswählen',
    qz_zero_questions: '0 Fragen',
    qz_settings: '⚙ Quiz-Einstellungen',
    qz_pick_quiz: 'Wähle ein Quiz, um zu starten.',
    qz_previous: '◀ Zurück',
    qz_submit: 'Absenden',
    qz_next: 'Weiter ▶',
    wc_card_title: 'Deutsch-Schreibtrainer',
    wc_card_sub: 'Deutscher Schreibtrainer · schreibe einen Absatz und erhalte KI-Feedback passend zu deinem Niveau',
    wc_back: '← Zurück',
    wc_view_sub: 'Schreibe einen deutschen Absatz und erhalte KI-Feedback passend zu deinem Niveau.',
    wc_no_level_title: 'Lege zuerst dein Deutschniveau im Profil fest',
    wc_no_level_sub: 'Der Schreibtrainer bewertet deinen Text anhand des Niveaus in deinem Profil. Öffne dein Profil, setze dein Niveau (z. B. B2 oder C1 Hochschule) und komm dann hierher zurück.',
    wc_go_profile: 'Zum Profil',
    wc_feedback_level: 'Feedback-Niveau',
    wc_level_title: 'Niveau im Profil bearbeiten',
    wc_level_source: 'Aus dem Profil übernommen',
    wc_text_type: 'Textart',
    wc_input_ph: 'Schreibe deinen deutschen Absatz hier…',
    wc_analyze: 'Mit KI analysieren',
    wc_analyzing: 'Analysiere…',
    gl_hero_eyebrow: 'Sprachtraining',
    gl_title: 'Deutsch lernen',
    gl_sub: 'Trainiere Lesen, Hören, Schreiben, Sprechen, Wortschatz und Grammatik in einem fokussierten Vorbereitungsbereich.',
    gl_avg_progress: 'Fortschritt im Schnitt',
    gl_this_week: 'diese Woche',
    gl_ai_writing_coach: 'KI-Schreibtrainer',
    gl_imported_profile: 'Aus deinem Profil übernommen',
    gl_start_practice: 'Übung starten',
    gl_reading_aria: 'Leseverstehen-Übung öffnen',
    gl_reading_sub: 'Leseverstehen',
    gl_listening_aria: 'Hörverstehen-Übung öffnen',
    gl_listening_sub: 'Hörverstehen',
    gl_writing_aria: 'Schreibübung öffnen',
    gl_writing_sub: 'Schreibaufgaben',
    gl_ai_feedback: 'KI-Feedback',
    gl_speaking_aria: 'Sprechübung öffnen',
    gl_speaking_sub: 'Sprechübungen',
    gl_practice_mode: 'Übungsmodus',
    gl_vocab_aria: 'Wortschatzübung öffnen',
    gl_vocab_sub: 'Wortschatztraining',
    gl_grammar_aria: 'Grammatikübung öffnen',
    gl_grammar_sub: 'Grammatiktraining',
    gl_practice_progress: 'Übungsfortschritt',
    gl_open_practice: 'Übung öffnen',
    sub_title: '⭐ Abonnement',
    sub_subtitle: 'Pro 7 Tage gratis testen, danach 11,99 €/Monat',
    sub_badge_popular: '🔥 Am beliebtesten',
    sub_plan_name: 'Pro',
    sub_trial_badge: '7 Tage kostenlos',
    sub_price_suffix: '/ Monat nach Test',
    sub_feat_ai: 'Großzügige KI-Nutzung (Fair-Use: 2000 Chats · 200 Generierungen / Monat)',
    sub_feat_pdf: 'PDF-Reader',
    sub_feat_notes: 'Unbegrenzte Vorlesungsnotizen',
    sub_feat_multi: 'Multi-PDF-Zusammenfassungen',
    sub_feat_support: 'Priorisierter Support',
    sub_feat_chat: 'Chaträume',
    sub_active: '✓ Aktives Abonnement',
    sub_manage: '⚙️ Abo verwalten / kündigen',
    sub_cancel_note: 'Jederzeit kündbar. Keine Abbuchung während der Testphase.',
    sub_usage_chat: 'Chat & Tutor diesen Monat',
    sub_usage_gen: 'Quiz / Karteikarten / Notizen-Generierungen',
    sub_pay_with: 'Bezahlen mit',
    sub_pay_card: '💳 Karte',
    sub_start_trial: 'Kostenlose 7-Tage-Testphase starten',
    sub_subscribe: 'Abonnieren — 11,99 €/Monat',
    sub_upgrade: 'Auf Pro upgraden',
    sub_pro_activated: 'Pro aktiviert!',
    sub_pro_enjoy: 'Genieße uneingeschränkten Zugriff.',
    sub_payment_received: 'Zahlung erhalten',
    sub_activating: 'Pro-Plan wird aktiviert...',
    sub_activation_error: 'Aktivierungsfehler',
    sub_activation_error_sub: 'Bitte Support kontaktieren.',
    sub_paypal_error: 'PayPal-Fehler',
    sub_paypal_error_default: 'Bitte erneut versuchen oder Karte verwenden.',
    sub_payment_unavailable: 'Zahlung nicht verfügbar',
    sub_payment_unavailable_sub: 'Abo-Konfiguration fehlt.',
    sub_payment_success: 'Zahlung erfolgreich!',
    pw_welcome: 'Willkommen bei Minallo',
    pw_desc: 'Starte deine kostenlose 7-Tage-Testphase, um alle Funktionen zu nutzen. Keine Abbuchung bis zum Ende der Testphase.',
    pw_desc_trialed: 'Abonniere, um alle Minallo-Funktionen für 11,99 €/Monat zu nutzen.',
    pw_trial_badge: '✨ 7 Tage kostenlos',
    pw_after_trial: '/ Monat nach Test',
    pw_feat_ai: 'Großzügige KI-Nutzung (Fair-Use: 2000 Chats · 200 Generierungen / Monat)',
    pw_feat_pdf: 'PDF-Reader & Vorlesungsnotizen',
    pw_feat_multi: 'Multi-PDF-Zusammenfassungen',
    pw_feat_chat: 'Chaträume',
    pw_feat_support: 'Priorisierter Support',
    pw_cancel_note: 'Jederzeit kündbar. Keine Abbuchung während der Testphase.',
    pw_pay_methods: 'Zahlung mit Karte · Klarna · PayPal',
    pw_signout: 'Abmelden',
    dash_empty_title: 'Deine Übersicht ist leer',
    dash_empty_sub_pre: 'Klicke ',
    dash_empty_sub_post: ' um Widgets hinzuzufügen',
    wp_title: '✶ Widgets hinzufügen',
    dash_no_courses: 'Noch keine Kurse — füge welche unter Fächer hinzu',
    dash_no_courses_short: 'Noch keine Kurse',
    gcw_connect_btn: 'Google Kalender verbinden',
    gcw_connect_sub: 'Mit Google anmelden, um deine Termine anzuzeigen und zu bearbeiten',
    mastery_take_quiz: 'Mache ein Quiz, um deinen Lernstand für diesen Kurs zu sehen.',
    wdg_courses_name: 'Kurs-Shortcuts',
    wdg_courses_desc: 'Direkt in einen Kurs springen',
    wdg_mail_name: 'Neue E-Mails',
    wdg_mail_desc: 'Nur ungelesene Nachrichten',
    wdg_notes_name: 'Schnellnotizen',
    wdg_notes_desc: 'Persönlicher Notizblock',
    wdg_stats_name: 'Lernstatistik',
    wdg_stats_desc: 'Wochenfortschritt',
    wdg_deadlines_name: 'Fristen',
    wdg_deadlines_desc: 'Bevorstehende Termine',
    wdg_weather_name: 'Campus-Wetter',
    wdg_weather_desc: 'Braunschweig-Vorhersage',
    wdg_ai_name: 'KI-Schnellchat',
    wdg_ai_desc: 'Sofort alles fragen',
    wdg_gcal_name: 'Google Kalender',
    wdg_gcal_desc: 'Termine anzeigen & bearbeiten',
    wdg_mastery_name: 'Übungsfokus',
    wdg_mastery_desc: 'Themen zum Vertiefen aus deinen Quizzes',
    auth_email_label: 'E-Mail',
    auth_password_label: 'Passwort',
    auth_confirm_label: 'Passwort bestätigen',
    auth_title_signin: 'Bei deinem Konto anmelden',
    auth_title_signup: 'Konto erstellen',
    auth_submit_signin: 'Anmelden',
    auth_submit_signup: 'Konto erstellen',
    auth_google_btn: 'Mit Google fortfahren',
    auth_stay: 'Angemeldet bleiben',
    auth_stay_timeout: '(30 Min. Timeout)',
    auth_switch_signin: 'Kein Konto? Registrieren',
    auth_switch_signup: 'Bereits ein Konto? Anmelden',
    auth_brand_tagline: 'Klüger lernen',
    auth_badge_signin: 'Willkommen zurück',
    auth_badge_signup: 'Willkommen bei Minallo',
    auth_heading_signin: 'Melde dich in deinem Lernbereich an.',
    auth_heading_signup: 'Erstelle dein Minallo-Konto.',
    auth_body_signin: 'Setze deine Kurse, Deutsch-Übungen, PDF-Arbeit, Playlists, Spiele und Fokus-Sessions in einer ruhigen Übersicht fort.',
    auth_body_signup: 'Organisiere dein Lernleben mit KI-Hilfe, PDF-Tools, Deutsch-Übungen, Fokus-Sessions, Playlists und Lernspielen.',
    auth_pw_toggle_aria: 'Passwort anzeigen oder verbergen',
    auth_pw_toggle_title: 'Passwort ein-/ausblenden',
    auth_email_ph: 'deine@email.com',
    auth_forgot: 'Passwort vergessen?',
    auth_or: 'oder',
    auth_google_signup_btn: 'Mit Google registrieren',
    auth_switch_prefix_signin: 'Noch kein Konto?',
    auth_switch_prefix_signup: 'Bereits ein Konto?',
    auth_switch_link_signup: 'Registrieren',
    auth_switch_link_signin: 'Anmelden',
    auth_submit_signin_short: 'Anmelden',
    auth_submit_signup_short: 'Konto erstellen',
    auth_buddy_pill: '24/7 Lernbegleiter',
    auth_buddy_title: 'Dein Minallo-Lernbuddy',
    auth_buddy_body: 'Stelle Fragen, organisiere deine Arbeit, übe Deutsch und bleib fokussiert — ohne zwischen Tools zu wechseln.',
    auth_mini_ai_title: 'KI-Tutor',
    auth_mini_ai_desc: 'Kursbezogene Hilfe mit Quellenangaben.',
    auth_mini_pdf_title: 'PDF-Arbeitsbereich',
    auth_mini_pdf_desc: 'Lesen, bearbeiten und Notizen ordnen.',
    auth_mini_focus_title: 'Fokus-Modus',
    auth_mini_focus_desc: 'Pomodoro-Sessions und Lernserien.',
    auth_mini_de_title: 'Deutsch üben',
    auth_mini_de_desc: 'Vokabular, Grammatik und Beispiele.',
    auth_pw_match: 'Passwörter stimmen überein',
    auth_pw_no_match: 'Passwörter stimmen nicht überein',
    auth_please_wait: 'Bitte warten...',
    ob_step1: 'Profil einrichten — Schritt 1 von 3',
    ob_step2: 'Erzähl uns von dir — Schritt 2 von 3',
    ob_step3: 'Details — Schritt 3 von 3',
    ob_welcome_title: 'Willkommen bei Minallo!',
    ob_path_title: 'Dein Weg',
    ob_almost_there: 'Fast geschafft!',
    ob_de_journey: 'Deine Deutsch-Reise',
    ob_log_out: 'Abmelden',
    ob_first_name: 'Vorname',
    ob_last_name: 'Nachname',
    ob_age: 'Alter',
    ob_email: 'E-Mail',
    ob_first_name_ph: 'z. B. Mohamed',
    ob_last_name_ph: 'z. B. Al-Rashid',
    ob_age_ph: 'z. B. 21',
    ob_email_ph: 'z. B. deine@email.com',
    ob_programme: 'Studiengang',
    ob_programme_ph: 'z. B. Maschinenbau',
    ob_semester: 'Semester',
    ob_semester_ph: 'z. B. 3',
    ob_matrikel: 'Matrikelnummer',
    ob_matrikel_ph: 'z. B. 2456789',
    ob_continue_btn: 'Weiter',
    ob_back_btn: '← Zurück',
    ob_finish_btn: 'Fertig',
    ob_saving: '⏳ Speichere…',
    ob_prompt_describe: 'Was trifft am besten auf dich zu?',
    ob_path_uni: 'Uni-Studierende:r',
    ob_path_uni_sub: 'Bereits an einer deutschen Hochschule eingeschrieben',
    ob_path_learner: 'Deutsch-Lernende:r',
    ob_path_learner_sub: 'Vorbereitung auf eine Sprachprüfung zur Einschreibung',
    ob_bundesland: 'Bundesland',
    ob_bundesland_ph: 'Wähle dein Bundesland…',
    ob_university: 'Universität',
    ob_uni_ph_before: 'Wähle zuerst ein Bundesland',
    ob_uni_ph_after: 'z. B. TU Braunschweig',
    ob_vertiefung: 'Vertiefung (Fachprofil)',
    ob_vertiefung_ph: 'z. B. Mechatronik',
    ob_vertiefung_optional_ph: 'Spezialisierung eingeben (optional)',
    ob_which_test: 'Auf welche Prüfung bereitest du dich vor?',
    ob_test_telc_sub: 'The European Language Certificates',
    ob_test_goethe_sub: 'Sprachzertifikat des Goethe-Instituts',
    ob_level_question: 'Was ist dein aktuelles / Ziel-Niveau?',
    ob_err_fill_all: 'Bitte alle Felder ausfüllen',
    ob_err_valid_email: 'Bitte eine gültige E-Mail eingeben',
    ob_err_bundesland: 'Bitte wähle dein Bundesland',
    ob_err_pick_uni: 'Bitte wähle eine Universität aus der Liste',
    ob_err_select_test: 'Bitte wähle eine Prüfung',
    ob_err_select_level: 'Bitte wähle dein Niveau',
    ob_save_failed_prefix: 'Speichern fehlgeschlagen: ',
    auth_pw_weak: 'Schwach',
    auth_pw_fair: 'Okay',
    auth_pw_good: 'Gut',
    auth_pw_strong: 'Stark',
    auth_user_fallback: 'Nutzer',
    auth_confirm_signout: 'Von Minallo abmelden?',
    settings_save_btn: 'Änderungen speichern',
    card_studip_desc: 'Kurse & Materialien',
    card_mail_desc: 'Outlook Web-Zugang',
    card_connect_desc: 'Prüfungen & Noten',
    card_timetable_name: 'Stundenplan',
    card_timetable_desc: 'Semesterplan',
    card_cert_name: 'Zertifikate',
    card_cert_desc: 'Immatrikulationsdokumente',
    profile_label_name: 'Vollständiger Name',
    profile_label_email: 'E-Mail',
    profile_label_university: 'Universität',
    profile_label_programme: 'Studiengang',
    profile_label_matrikel: 'Matrikelnummer',
    profile_save_btn: '💾 Änderungen speichern',
    settings_appearance: 'Erscheinungsbild',
    settings_dark_mode: 'Dunkelmodus',
    settings_language: 'Sprache',
    settings_ai_section: 'KI-Assistent',
    settings_auto_open: 'Automatisch bei Textauswahl öffnen',
    settings_save_chat: 'Chatverlauf pro PDF speichern',
    settings_notifications: 'Benachrichtigungen',
    settings_sync_alerts: 'Vorlesungsnotiz-Synchronisierung',
    settings_mail_alerts: 'Neue E-Mail-Benachrichtigungen',
    settings_data: 'Daten',
    settings_clear_chat: 'Gesamten KI-Chatverlauf löschen',
    settings_clear_btn: 'Verlauf löschen',
    settings_account: 'Konto',
    settings_signout: 'Von Minallo abmelden',
    settings_logout_btn: 'Abmelden',
    ln_title: '🎬 Vorlesungsnotizen',
    ln_sync_btn: 'Von Erweiterung synchronisieren',
    sb_subjects: '📚 Fächer',
    sb_timetable: '🗓️ Stundenplan',
    sb_mails: '✉️ E-Mails',
    sb_back: '← Alle Fächer',
    back_btn: '← Zurück',
    pdf_fit: 'Anpassen',
    pdf_single: 'Einzelseite',
    pdf_download: '⬇ Herunterladen',
    ai_ready: 'Bereit zu helfen',
    chip_summarise: '✨ Zusammenfassen',
    chip_formulas: '🔢 Formeln',
    chip_quiz: '📝 Quiz',
    chip_keyideas: '💡 Kernideen',
    chip_analogy: '🔗 Analogie',
    depth_label: 'Tiefe:',
    chip_brief: 'Kurz',
    chip_standard: 'Standard',
    chip_thorough: 'Ausführlich',
    level_label: 'Niveau:',
    chip_easy: 'Einfach',
    chip_medium: 'Mittel',
    chip_hard: 'Schwer',
    stop_btn: '⏹ Stopp',
    ai_placeholder: 'Stelle eine Frage zu diesem Dokument…',
    ai_welcome: 'Hey! 👋 Öffne ein PDF, markiere Text oder eine Formel und ich helfe dir!',
    ai_tip_no_pdf: '💡 Tipp: Öffne zuerst ein PDF, damit ich aus dem Dokument antworten kann!',
    ai_file_loaded_post:
      'geladen! Stelle mir beliebige Fragen — ich antworte anhand des Dokuments. 🎓',
    ai_chat_cleared_msg: 'Chat gelöscht! Was möchtest du wissen? 😊',
    chat_restored: '— Chatverlauf wiederhergestellt —',
    no_file_open: 'Keine Datei geöffnet',
    loading_pdf: 'PDF wird geladen…',
    not_in_demo: 'Diese Datei ist in der Demo nicht verfügbar.',
    not_in_demo_multi: 'in der Demo nicht verfügbar',
    download_failed: 'Download fehlgeschlagen.',
    copy_btn: 'Kopieren',
    you_label: 'Du',
    nothing_yet: 'Noch nichts hier',
    studip_subtitle: 'TU Braunschweig · Deine Kurse & Materialien',
    studip_back: '← Portal',
    sd_subjects: '📚 Fächer',
    sd_timetable: '🗓️ Stundenplan',
    sd_mails: '✉️ E-Mails',
    sel_explain: 'Erklären',
    sel_formula: 'Formel aufschlüsseln',
    sel_dismiss: 'Schließen',
    sel_preview: '📌 Du hast ausgewählt:',
    sync_syncing: 'Synchronisiere…',
    sync_synced: 'Synchronisiert ✓',
    sync_no_ext: 'Erweiterung nicht gefunden',
    toast_saved: '💾 In Vorlesungsnotizen gespeichert',
    toast_new_summary_pre: '📝 Neue Zusammenfassung: ',
    toast_tap_view: 'Tippe auf Ansehen um deine Notizen zu öffnen',
    toast_synced_s: 'Notiz synchronisiert',
    toast_synced_p: 'Notizen synchronisiert',
    toast_no_notes: '⚠️ Keine Notizen gefunden',
    toast_summarize_first: 'Fasse zuerst eine Vorlesung in der Erweiterung zusammen',
    toast_sign_in: '⚠️ Anmelden zum Speichern',
    toast_profile_saved: '✅ Profil gespeichert',
    toast_profile_saved_sub: 'In deinem Konto gespeichert',
    toast_save_failed: '❌ Speichern fehlgeschlagen',
    toast_chat_cleared: '🗑️ Chatverlauf gelöscht',
    toast_chat_cleared_sub: 'Alle gespeicherten Chats wurden entfernt',
    toast_settings_saved: '✅ Einstellungen gespeichert',
    toast_settings_saved_sub: 'Deine Einstellungen wurden aktualisiert',
    toast_signed_out: '👋 Abgemeldet',
    toast_signed_out_sub: 'Bis zum nächsten Mal!',
    toast_coming_soon: '🚀 Demnächst',
    toast_coming_soon_sub: 'Zahlungsintegration kommt bald!',
    toast_inactivity: '⏰ Wegen Inaktivität abgemeldet',
    toast_inactivity_sub: 'Melde dich erneut an um fortzufahren',
    err_connection: 'Verbindungsfehler — bitte Seite neu laden',
    err_fill_fields: 'Bitte alle Felder ausfüllen',
    err_confirm_pw: 'Bitte Passwort bestätigen',
    err_pw_mismatch: 'Passwörter stimmen nicht überein',
    err_pw_length: 'Passwort muss mindestens 8 Zeichen haben',
    err_account_created: '✅ Konto erstellt! Prüfe deine E-Mail und klicke den Bestätigungslink.',
    err_confirm_email: '⚠️ Bitte bestätige zuerst deine E-Mail — schau in deinen Posteingang.',
    err_wrong_pw:
      '⚠️ Falsches Passwort — oder hast du dich mit Google angemeldet? Versuche den Google-Button unten oder erstelle ein neues Konto.',
    err_network: 'Netzwerkfehler — überprüfe deine Verbindung.',
    aip_new_chat: 'Neuer Chat',
    aip_chats_label: 'Chats',
    aip_no_chats: 'Noch keine Chats',
    aip_subtitle: 'Womit fangen wir an?',
    aip_landing_ph: 'Frag mich alles…',
    aip_followup_ph: 'Stelle eine Folgefrage…',
    aip_upload_btn: 'Fotos & Dateien hochladen',
    set_unsaved: 'Ungespeicherte Änderungen',
    set_saving: 'Speichere…',
    set_saved: 'Gespeichert ✓',
    set_save_failed: 'Speichern fehlgeschlagen',
    set_deleting: 'Lösche...',
    set_yes_delete: 'Ja, löschen',
    sub_loading: 'Lädt...',
    sub_redirecting: 'Weiterleitung...',
    sub_not_available: 'Nicht verfügbar',
    sub_no_stripe: 'Kein Stripe-Konto gefunden.',
    sub_error: 'Fehler',
    sub_portal_failed: 'Portal konnte nicht geöffnet werden.',
    sub_signin_required: 'Anmeldung erforderlich',
    sub_login_first: 'Bitte zuerst anmelden.',
    sub_checkout_failed: 'Checkout konnte nicht gestartet werden.',
    cb_header_title: 'Chatbot',
    cb_header_subtitle: 'Kurs-bewusster KI-Tutor',
    cb_open_panel: 'Kontextpanel öffnen',
    cb_close_panel: 'Kontextpanel schließen',
    cb_sidebar_eyebrow: 'Minallo',
    cb_sidebar_title: 'KI-Chats',
    cb_collapse_sidebar: 'Seitenleiste einklappen',
    cb_new_chat: 'Neuer Chat',
    cb_search_chats: 'Chats suchen...',
    cb_search_chats_aria: 'Chats suchen',
    cb_safe_title: 'Kurssicherer Modus',
    cb_safe_text: 'Antworten können auf hochgeladene Vorlesungen, Übungen und Kursdateien beschränkt werden.',
    cb_current_chat: 'Aktueller Chat',
    cb_chat_title_new: 'Neuer Chat',
    cb_context_active: 'Kurskontext aktiv',
    cb_empty_title: 'Was lernen wir heute?',
    cb_empty_subtitle: 'Lade eine Vorlesung hoch, importiere eine Kursdatei, löse eine Übung, erstelle Notizen oder lass Minallo das Thema wie ein persönlicher Tutor erklären.',
    cb_greet_ready: 'Bereit, klüger zu lernen?',
    cb_tutor_solve: 'Gemeinsam lösen',
    cb_tutor_solve_title: 'Sokratisch — führt dich Schritt für Schritt, statt die Lösung zu verraten',
    cb_tutor_explain: 'Erklären',
    cb_tutor_explain_title: 'Direkte Erklärung, gestützt auf deine Kursdateien',
    cb_tutor_quiz: 'Quiz mich',
    cb_tutor_quiz_title: 'Erstellt einen kurzen MCQ-Check zu diesem Thema aus deinen Kursdateien',
    cb_tutor_group_aria: 'Tutor-Modus',
    cb_upload_btn: 'Fotos & Dateien hochladen',
    cb_import_btn: 'Aus Kurs importieren',
    cb_input_placeholder: 'Frag etwas zu deinen Vorlesungen, Übungen oder Kursdateien...',
    cb_input_aria: 'Nachricht eingeben',
    cb_send_btn: 'Nachricht senden',
    cb_action_summarize_title: 'Vorlesung zusammenfassen',
    cb_action_summarize_desc: 'PDFs in saubere Notizen verwandeln',
    cb_action_solve_title: 'Übung lösen',
    cb_action_solve_desc: 'Schritt für Schritt mit Formeln',
    cb_action_exam_title: 'Klausurantwort',
    cb_action_exam_desc: 'Kurz, strukturiert, präzise',
    cb_action_flash_title: 'Karteikarten erstellen',
    cb_action_flash_desc: 'Kernkonzepte schnell sichern',
    cb_ctx_eyebrow: 'Kontext',
    cb_ctx_title: 'Lernpanel',
    cb_tab_files: 'Dateien',
    cb_tab_sources: 'Quellen',
    cb_tab_notes: 'Notizen',
    cb_notes_card_title: 'Gespeicherte Antworten',
    cb_notes_empty: 'Speichere hilfreiche KI-Antworten hier, indem du unter einer Antwort auf „In Notizen speichern“ tippst.',
    cb_sources_card_title: 'Verwendete Quellen',
    cb_sources_count_zero: '0 Dateien',
    cb_tools_title: 'KI-Tools',
    cb_tool_quiz: 'Quiz mich',
    cb_tool_flashcards: 'Karteikarten',
    cb_tool_summary: 'Zusammenfassung',
    cb_tool_export: 'Export',
    cb_streak_title: 'Lernserie',
    cb_streak_text: 'Du bist nur eine fokussierte Session davon entfernt, deine heutige Serie am Leben zu halten.',
    cb_modal_eyebrow: 'Kursdateien',
    cb_modal_title: 'Aus Kurs importieren',
    cb_modal_close: 'Schließen',
    cb_modal_course_aria: 'Kurs',
    cb_modal_search_ph: 'Ordner oder Dateien suchen...',
    cb_modal_search_aria: 'Ordner oder Dateien suchen',
    cb_modal_back: 'Zurück',
    cb_modal_hint_title: 'Smart-Import',
    cb_modal_hint_text: 'Importierte Kursdateien werden an diesen Chat-Kontext angehängt und können für Zitate, Zusammenfassungen und Übungslösungen verwendet werden.',
    cb_modal_folder_selected: 'Ordner ausgewählt',
    cb_modal_folders_selected: 'Ordner ausgewählt',
    cb_modal_cancel: 'Abbrechen',
    cb_modal_import: 'Importieren',
    cb_response_stopped: 'Antwort gestoppt.',
    cb_request_failed: 'Anfrage fehlgeschlagen.',
    cb_no_response: 'Keine Antwort.',
    cb_error_prefix: '❌ Fehler: ',
    cb_verified: '✓ Verifiziert',
    cb_partially_verified: '⚠ Teilweise verifiziert',
    cb_missing_context: '⚠ Kontext fehlt',
    cb_sources_summary: 'Quellen',
    cb_sender_minallo: 'Minallo KI',
    cb_answered_using_context: 'Mit Kurskontext beantwortet',
    cb_stop_response_aria: 'KI-Antwort stoppen',
    cb_pasted_screenshot: 'Eingefügter Screenshot',
    cb_act_copy: 'Kopieren',
    cb_act_regen: 'Neu generieren',
    cb_act_bookmark: 'Lesezeichen',
    cb_act_bookmark_title: 'Diese Antwort speichern',
    cb_act_thumb_up: 'Daumen hoch',
    cb_act_thumb_down: 'Daumen runter',
    cb_act_copied: 'Kopiert',
    cb_act_saved: 'Gespeichert',
    cb_act_already_saved: 'Bereits gespeichert',
    cb_act_busy: 'Beschäftigt',
    cb_act_nothing_export: 'Nichts zu exportieren',
    cb_act_exported: 'Exportiert',
    cb_untitled_course: 'Kurs ohne Titel',
    cb_open_course_first: 'Öffne zuerst einen Kurs auf Minallo, um seine Dateien hier zu importieren.',
    cb_no_files_in_folder: 'Keine Dateien in diesem Ordner.',
    cb_no_matches: 'Keine Treffer.',
    cb_no_files_in_course: 'Keine Dateien in diesem Kurs.',
    cb_importing: 'Importiere…',
    cb_remove_saved_reply: 'Gespeicherte Antwort entfernen',
    cb_section_pinned: 'Angeheftet',
    cb_section_recent: 'Aktuell',
    cb_clear_all: 'Alle Chats löschen',
    cb_clear_all_confirm: 'Alle Chats in der Seitenleiste löschen? Das kann nicht rückgängig gemacht werden.',
    cb_storage_full_title: 'Chat-Speicher voll',
    cb_storage_full_text: 'Browser-Speicher ist voll. Lösche einige Chats, damit neue beim Neuladen nicht verloren gehen.',
    cb_storage_blocked_title: 'Chats nicht gespeichert',
    cb_storage_blocked_text: 'Dein Browser hat den Speicher blockiert (Privatmodus?). Chats bleiben beim Neuladen nicht erhalten.',
    cb_menu_pin: 'Anheften',
    cb_menu_unpin: 'Lösen',
    cb_menu_rename: 'Umbenennen',
    cb_menu_delete: 'Löschen',
    cb_rename_chat_aria: 'Chat umbenennen',
    cb_empty_draft: 'Leerer Entwurf',
  },
};

export function t(key: string): string {
  const lang = localStorage.getItem('ss_lang') || 'en';
  return (translations[lang] || translations.en!)[key] || key;
}

export function applyLanguage(lang: string): void {
  const _lang = lang === 'de' ? 'de' : 'en';
  localStorage.setItem('ss_lang', _lang);
  window._lang = _lang;
  window._t = (key: string): string =>
    (translations[_lang] || translations.en!)[key] || key;
  const tr = translations[_lang]!;
  document.querySelectorAll<HTMLElement>('[data-i18n]').forEach((el) => {
    const key = el.getAttribute('data-i18n');
    if (key && tr[key] !== undefined) el.textContent = tr[key]!;
  });
  document.querySelectorAll<HTMLElement>('[data-i18n-ph]').forEach((el) => {
    const key = el.getAttribute('data-i18n-ph');
    if (key && tr[key] !== undefined) {
      (el as HTMLInputElement).placeholder = tr[key]!;
    }
  });
  document.querySelectorAll<HTMLElement>('[data-i18n-title]').forEach((el) => {
    const key = el.getAttribute('data-i18n-title');
    if (key && tr[key] !== undefined) el.setAttribute('title', tr[key]!);
  });
  document.querySelectorAll<HTMLElement>('[data-i18n-aria]').forEach((el) => {
    const key = el.getAttribute('data-i18n-aria');
    if (key && tr[key] !== undefined) el.setAttribute('aria-label', tr[key]!);
  });
  const langSel = document.getElementById('settingsLanguage') as HTMLSelectElement | null;
  if (langSel) langSel.value = _lang;
  if (typeof window._setAuthMode === 'function') {
    window._setAuthMode((window._authMode as 'signin' | 'signup') || 'signin');
  }
  const obSub = document.getElementById('obSub');
  if (obSub) {
    const key = obSub.getAttribute('data-i18n');
    if (key) obSub.textContent = tr[key] || obSub.textContent;
  }
  const ssb = document.getElementById('saveSettingsBtn');
  if (ssb) ssb.textContent = tr.settings_save_btn || ssb.textContent;
  const chipName = document.getElementById('aiFileChipName');
  if (
    chipName &&
    (chipName.textContent === translations.en!.no_file_open ||
      chipName.textContent === translations.de!.no_file_open)
  ) {
    chipName.textContent = tr.no_file_open!;
  }
  const aiFileLabel = document.getElementById('aiFileLabel');
  if (
    aiFileLabel &&
    (aiFileLabel.textContent === translations.en!.ai_ready ||
      aiFileLabel.textContent === translations.de!.ai_ready)
  ) {
    aiFileLabel.textContent = tr.ai_ready!;
  }
  const studipSub = document.getElementById('studipSubtitle');
  if (studipSub) studipSub.textContent = tr.studip_subtitle!;
  const studipBackBtn = document.getElementById('studipBack');
  if (studipBackBtn) studipBackBtn.textContent = tr.studip_back!;
  const sdSubj = document.getElementById('sdSubjectsLabel');
  if (sdSubj) sdSubj.textContent = tr.sd_subjects!;
  const sdTT = document.getElementById('sdTimetableLabel');
  if (sdTT) sdTT.textContent = tr.sd_timetable!;
  const sdMail = document.getElementById('sdMailsLabel');
  if (sdMail) sdMail.textContent = tr.sd_mails!;
  const landingBtn = document.getElementById('landingLangBtn');
  if (landingBtn && typeof window._toggleLandingLang !== 'undefined') {
    landingBtn.textContent = _lang === 'de' ? 'EN' : 'DE';
  }
  // Notify any view that renders strings via JS (dashboard widgets, picker, etc.)
  // so they can re-render with the new language.
  try {
    window.dispatchEvent(new CustomEvent('minallo:lang-changed', { detail: { lang: _lang } }));
  } catch {
    /* ignore */
  }
}
