// AUTO-GENERATED by scripts/generate-pages-shims.mjs - kept in sync with ai-generate.
import { handler } from '../../../backend/functions/ai-cheatsheet';
import { pagesAdapter } from '../../../backend/lib/pages-adapter';

export const onRequest = pagesAdapter(handler);
