import js from '@eslint/js';

const nodeGlobals = {
  process: 'readonly',
  require: 'readonly',
  module: 'readonly',
  exports: 'readonly',
  Buffer: 'readonly',
  __dirname: 'readonly',
  __filename: 'readonly',
  console: 'readonly',
  setTimeout: 'readonly',
  setInterval: 'readonly',
  clearTimeout: 'readonly',
  clearInterval: 'readonly',
  setImmediate: 'readonly',
  clearImmediate: 'readonly',
  Promise: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  fetch: 'readonly',
  global: 'readonly',
  globalThis: 'readonly',
  TextDecoder: 'readonly',
  TextEncoder: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  FormData: 'readonly',
  Blob: 'readonly',
  File: 'readonly',
  Headers: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  crypto: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  structuredClone: 'readonly'
};

const browserGlobals = {
  // Web platform
  window: 'readonly',
  document: 'readonly',
  navigator: 'readonly',
  console: 'readonly',
  location: 'readonly',
  history: 'readonly',
  performance: 'readonly',
  screen: 'readonly',
  setTimeout: 'readonly',
  setInterval: 'readonly',
  clearTimeout: 'readonly',
  clearInterval: 'readonly',
  requestAnimationFrame: 'readonly',
  cancelAnimationFrame: 'readonly',
  queueMicrotask: 'readonly',
  fetch: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  localStorage: 'readonly',
  sessionStorage: 'readonly',
  indexedDB: 'readonly',
  crypto: 'readonly',
  Promise: 'readonly',
  alert: 'readonly',
  confirm: 'readonly',
  prompt: 'readonly',
  open: 'readonly',
  close: 'readonly',
  FormData: 'readonly',
  File: 'readonly',
  Blob: 'readonly',
  FileReader: 'readonly',
  FileList: 'readonly',
  MutationObserver: 'readonly',
  IntersectionObserver: 'readonly',
  ResizeObserver: 'readonly',
  PerformanceObserver: 'readonly',
  CustomEvent: 'readonly',
  Event: 'readonly',
  EventTarget: 'readonly',
  HTMLElement: 'readonly',
  Element: 'readonly',
  Node: 'readonly',
  NodeList: 'readonly',
  DocumentFragment: 'readonly',
  Image: 'readonly',
  Audio: 'readonly',
  Worker: 'readonly',
  SharedWorker: 'readonly',
  WebSocket: 'readonly',
  XMLHttpRequest: 'readonly',
  TextDecoder: 'readonly',
  TextEncoder: 'readonly',
  AbortController: 'readonly',
  AbortSignal: 'readonly',
  Headers: 'readonly',
  Request: 'readonly',
  Response: 'readonly',
  atob: 'readonly',
  btoa: 'readonly',
  globalThis: 'readonly',
  structuredClone: 'readonly',
  // Third-party libs loaded via script tags
  supabase: 'readonly',
  pdfjsLib: 'readonly',
  marked: 'readonly',
  Stripe: 'readonly',
  paypal: 'readonly',
  google: 'readonly',
  hljs: 'readonly',
  confetti: 'readonly',
  // Project globals shared across script/module files
  SUPA_URL: 'writable',
  SUPA_KEY: 'writable',
  STRIPE_KEY: 'writable',
  APP_VERSION: 'writable',
  SEMS: 'writable',
  _currentUser: 'writable',
  _sbToken: 'writable',
  _sbClient: 'writable',
  _sbHeaders: 'writable',
  _supabase: 'writable',
  pdfDoc: 'writable',
  pdfPage: 'writable',
  pdfTotal: 'writable',
  pdfScale: 'writable',
  pdfFullText: 'writable',
  pdfShowAll: 'writable',
  activeCourseId: 'writable',
  activeCourseRef: 'writable',
  activeCourseSection: 'writable',
  activeSemId: 'writable',
  activeFileName: 'writable',
  activePortalSection: 'writable',
  _ssRestoring: 'writable',
  // Project functions defined in one file, used in others
  showToast: 'readonly',
  renderPages: 'readonly',
  loadPDF: 'readonly',
  getSupabase: 'readonly',
  getCurrentUser: 'readonly',
  getAuthToken: 'readonly',
  navigateTo: 'readonly',
  showPanel: 'readonly',
  hidePanel: 'readonly',
  openModal: 'readonly',
  closeModal: 'readonly',
  formatDate: 'readonly',
  escapeHtml: 'readonly',
  debounce: 'readonly',
  throttle: 'readonly',
  nightOn: 'readonly',
  setNavActive: 'readonly',
  showPortal: 'readonly',
  showPortalSection: 'readonly',
  showCourseSection: 'readonly',
  showSelectionBanner: 'readonly',
  showStudip: 'readonly',
  updateAuthIndicator: 'readonly',
  loadUserData: 'readonly',
  openFile: 'readonly',
  saveState: 'readonly',
  restoreState: 'readonly',
  sdRenderCourses: 'readonly',
  _navTo: 'readonly',
  _loungeRender: 'readonly',
  _chatInit: 'readonly',
  _initPayPalButton: 'readonly',
  _bindSubscriptionControls: 'readonly',
  _glActiveSkill: 'readonly',
  _glLoadFiles: 'readonly',
  _setAiChipsVisible: 'readonly',
  _showFilesView: 'readonly',
  _ssClearRestoredFileState: 'readonly',
  _ssEnsureJsPdf: 'readonly',
  _ssReplaceHistory: 'readonly',
  _ufMerge: 'readonly',
  _ufUpload: 'readonly'
};

export default [
  {
    ignores: ['node_modules/', 'backend/node_modules/', 'frontend/assets/', 'docs/', '.netlify/']
  },
  js.configs.recommended,
  {
    files: ['backend/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'commonjs',
      globals: nodeGlobals
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrors: 'none' }],
      'no-empty': 'warn',
      'no-undef': 'error',
      'no-control-regex': 'warn',
      'no-useless-escape': 'warn',
      'no-redeclare': 'warn'
    }
  },
  {
    files: ['frontend/js/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: browserGlobals
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrors: 'none' }],
      'no-empty': 'warn',
      'no-undef': 'warn',
      'no-control-regex': 'warn',
      'no-useless-escape': 'warn',
      'no-irregular-whitespace': 'warn',
      'no-redeclare': 'warn',
      'no-func-assign': 'warn'
    }
  }
];
