// AUTO-GENERATED by scripts/generate-pages-shims.mjs — do not edit by hand.
import { handler } from '../../backend/functions/join-room-by-code';
import { pagesAdapter } from '../../backend/lib/pages-adapter';

export const onRequest = pagesAdapter(handler);
