// AUTO-GENERATED by scripts/generate-pages-shims.mjs — do not edit by hand.
import { handler } from '../../backend/functions/paypal-webhook';
import { pagesAdapter } from '../../backend/lib/pages-adapter';

export const onRequest = pagesAdapter(handler, { rawBody: 'base64' });
