export async function aiMakePdfBlob(title, text) {
  await window._ssEnsurePdfExportDeps();
  var jsPDF = (window.jspdf && window.jspdf.jsPDF) || window.jsPDF;
  if (!jsPDF) {
    window.showToast('jsPDF missing', 'Could not build PDF');
    return null;
  }
  if (!window.html2canvas) {
    window.showToast('html2canvas missing', 'Could not render PDF');
    return null;
  }

  var container = document.createElement('div');
  container.style.cssText =
    'position:fixed;left:-9999px;top:0;width:750px;background:#ffffff;color:#1a1a1a;font-family:Arial,Helvetica,sans-serif;font-size:13px;line-height:1.75;padding:44px 52px;box-sizing:border-box;z-index:99999;';

  var titleEl = document.createElement('div');
  titleEl.style.cssText =
    'font-size:19px;font-weight:700;color:#5028a0;margin-bottom:10px;padding-bottom:10px;border-bottom:2px solid #9b5de5;';
  titleEl.textContent = title;
  container.appendChild(titleEl);

  var contentEl = document.createElement('div');
  contentEl.style.color = '#1a1a1a';
  contentEl.innerHTML = window.renderMarkdown ? window.renderMarkdown(text) : text;
  container.appendChild(contentEl);

  var footer = document.createElement('div');
  footer.style.cssText =
    'margin-top:32px;font-size:10px;color:#aaa;border-top:1px solid #eee;padding-top:8px;';
  footer.textContent = 'Generated by StudySphere AI';
  container.appendChild(footer);

  document.body.appendChild(container);

  try {
    await new Promise(function (r) {
      setTimeout(r, 60);
    });
    var canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
      logging: false
    });
    document.body.removeChild(container);

    var doc = new jsPDF({ unit: 'mm', format: 'a4' });
    var pageW = 210,
      pageH = 297,
      margin = 10;
    var imgW = pageW - margin * 2;
    var pageContentH = pageH - margin * 2;
    var pxPerMm = canvas.width / imgW;
    var srcYpx = 0;
    var firstPage = true;

    while (srcYpx < canvas.height) {
      if (!firstPage) doc.addPage();
      firstPage = false;
      var sliceHpx = Math.min(Math.round(pageContentH * pxPerMm), canvas.height - srcYpx);
      var sliceCanvas = document.createElement('canvas');
      sliceCanvas.width = canvas.width;
      sliceCanvas.height = sliceHpx;
      sliceCanvas
        .getContext('2d')
        .drawImage(canvas, 0, srcYpx, canvas.width, sliceHpx, 0, 0, canvas.width, sliceHpx);
      doc.addImage(
        sliceCanvas.toDataURL('image/png'),
        'PNG',
        margin,
        margin,
        imgW,
        sliceHpx / pxPerMm
      );
      srcYpx += sliceHpx;
    }

    return doc.output('blob');
  } catch (e) {
    if (document.body.contains(container)) document.body.removeChild(container);
    window.showToast('PDF error', e.message);
    return null;
  }
}

export async function aiDownloadPdf(title, text) {
  var blob = await aiMakePdfBlob(title, text);
  if (!blob) return;
  var url = URL.createObjectURL(blob);
  var a = document.createElement('a');
  a.href = url;
  a.download =
    title
      .slice(0, 60)
      .replace(/[^\w\s-]/g, '')
      .trim() + '.pdf';
  a.click();
  setTimeout(function () {
    URL.revokeObjectURL(url);
  }, 2000);
}

export function ufDestPicker(uid, course, onPick) {
  var overlay = document.createElement('div');
  overlay.style.cssText =
    'position:fixed;inset:0;background:rgba(0,0,0,.6);display:flex;align-items:center;justify-content:center;z-index:10001;';
  overlay.addEventListener('click', function (e) {
    if (e.target === overlay) overlay.remove();
  });
  var box = document.createElement('div');
  box.style.cssText =
    'background:var(--dp-solid);border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:22px 20px;max-width:340px;width:90%;max-height:75vh;overflow-y:auto;display:flex;flex-direction:column;gap:8px;';
  var hdr = document.createElement('div');
  hdr.style.cssText = 'font-weight:800;font-size:.95rem;color:var(--on-glass);margin-bottom:2px;';
  hdr.textContent = 'Where to export?';
  box.appendChild(hdr);
  var sub = document.createElement('div');
  sub.style.cssText = 'font-size:.78rem;color:var(--on-glass-faint);margin-bottom:6px;';
  sub.textContent = course.name || course.short;
  box.appendChild(sub);
  function addOpt(icon, label, onClick) {
    var b = document.createElement('button');
    b.style.cssText =
      'display:flex;align-items:center;gap:10px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:10px 14px;cursor:pointer;color:var(--on-glass);font-family:Nunito,sans-serif;font-size:.85rem;font-weight:700;text-align:left;width:100%;transition:background .13s;';
    b.innerHTML =
      '<span style="font-size:1.1rem">' + icon + '</span><span style="flex:1">' + label + '</span>';
    b.addEventListener('mouseenter', function () {
      b.style.background = 'rgba(155,93,229,.2)';
    });
    b.addEventListener('mouseleave', function () {
      b.style.background = 'rgba(255,255,255,.06)';
    });
    b.addEventListener('click', function () {
      overlay.remove();
      onClick();
    });
    box.appendChild(b);
  }
  addOpt('📁', 'Course root', function () {
    onPick(null);
  });
  if (window._ufGetFolders)
    window._ufGetFolders(uid, course).forEach(function (f) {
      addOpt('📂', f, function () {
        onPick(f);
      });
    });
  var nb = document.createElement('button');
  nb.style.cssText =
    'display:flex;align-items:center;gap:10px;background:rgba(155,93,229,.08);border:1px dashed rgba(155,93,229,.35);border-radius:12px;padding:10px 14px;cursor:pointer;color:var(--purple);font-family:Nunito,sans-serif;font-size:.85rem;font-weight:700;text-align:left;width:100%;margin-top:2px;';
  nb.innerHTML = '<span style="font-size:1.1rem">➕</span><span>New folder…</span>';
  nb.addEventListener('click', function () {
    var name = prompt('Folder name:');
    if (!name || !name.trim()) return;
    if (window._ufCreateFolder) window._ufCreateFolder(uid, course, name.trim());
    overlay.remove();
    onPick(name.trim());
  });
  box.appendChild(nb);
  var cancel = document.createElement('button');
  cancel.style.cssText =
    'margin-top:6px;background:transparent;border:none;color:rgba(255,255,255,.35);font-family:Nunito,sans-serif;font-size:.8rem;font-weight:700;cursor:pointer;padding:6px;border-radius:8px;transition:color .13s;';
  cancel.textContent = 'Cancel';
  cancel.addEventListener('mouseenter', function () {
    cancel.style.color = 'rgba(255,255,255,.6)';
  });
  cancel.addEventListener('mouseleave', function () {
    cancel.style.color = 'rgba(255,255,255,.35)';
  });
  cancel.addEventListener('click', function () {
    overlay.remove();
  });
  box.appendChild(cancel);
  overlay.appendChild(box);
  document.body.appendChild(overlay);
}

export function glMoveDestPicker(uid, fromCourse, onPick) {
  var isGL = fromCourse.id && fromCourse.id.startsWith('german-');
  if (!isGL) {
    ufDestPicker(uid, fromCourse, function (f) {
      onPick(fromCourse, f);
    });
    return;
  }

  function showFolderPicker(toCourse) {
    var overlay2 = document.createElement('div');
    overlay2.style.cssText =
      'position:fixed;inset:0;background:rgba(0,0,0,.6);display:flex;align-items:center;justify-content:center;z-index:10002;';
    overlay2.addEventListener('click', function (e) {
      if (e.target === overlay2) overlay2.remove();
    });
    var box2 = document.createElement('div');
    box2.style.cssText =
      'background:var(--dp-solid);border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:22px 20px;max-width:340px;width:90%;max-height:75vh;overflow-y:auto;display:flex;flex-direction:column;gap:8px;';
    var topRow = document.createElement('div');
    topRow.style.cssText = 'display:flex;align-items:center;gap:8px;margin-bottom:2px;';
    var backBtn = document.createElement('button');
    backBtn.style.cssText =
      'background:transparent;border:none;color:rgba(255,255,255,.5);font-family:Nunito,sans-serif;font-size:.8rem;font-weight:800;cursor:pointer;padding:4px 8px;border-radius:8px;transition:all .13s;flex-shrink:0;';
    backBtn.textContent = '← Back';
    backBtn.addEventListener('mouseenter', function () {
      backBtn.style.color = 'rgba(255,255,255,.85)';
      backBtn.style.background = 'rgba(255,255,255,.08)';
    });
    backBtn.addEventListener('mouseleave', function () {
      backBtn.style.color = 'rgba(255,255,255,.5)';
      backBtn.style.background = 'transparent';
    });
    backBtn.addEventListener('click', function () {
      overlay2.remove();
      showCardPicker();
    });
    var h2 = document.createElement('div');
    h2.style.cssText = 'font-weight:800;font-size:.95rem;color:var(--on-glass);flex:1;';
    h2.textContent = 'Folder in ' + (toCourse.name || toCourse.id);
    topRow.appendChild(backBtn);
    topRow.appendChild(h2);
    box2.appendChild(topRow);
    function addOpt2(icon, label, onClick) {
      var b = document.createElement('button');
      b.style.cssText =
        'display:flex;align-items:center;gap:10px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:10px 14px;cursor:pointer;color:var(--on-glass);font-family:Nunito,sans-serif;font-size:.85rem;font-weight:700;text-align:left;width:100%;transition:background .13s;';
      b.innerHTML =
        '<span style="font-size:1.1rem">' +
        icon +
        '</span><span style="flex:1">' +
        label +
        '</span>';
      b.addEventListener('mouseenter', function () {
        b.style.background = 'rgba(155,93,229,.2)';
      });
      b.addEventListener('mouseleave', function () {
        b.style.background = 'rgba(255,255,255,.06)';
      });
      b.addEventListener('click', function () {
        overlay2.remove();
        onClick();
      });
      box2.appendChild(b);
    }
    addOpt2('📁', 'Root (no folder)', function () {
      onPick(toCourse, null);
    });
    if (window._ufGetFolders)
      window._ufGetFolders(uid, toCourse).forEach(function (f) {
        addOpt2('📂', f, function () {
          onPick(toCourse, f);
        });
      });
    var nb2 = document.createElement('button');
    nb2.style.cssText =
      'display:flex;align-items:center;gap:10px;background:rgba(155,93,229,.08);border:1px dashed rgba(155,93,229,.35);border-radius:12px;padding:10px 14px;cursor:pointer;color:var(--purple);font-family:Nunito,sans-serif;font-size:.85rem;font-weight:700;text-align:left;width:100%;margin-top:2px;';
    nb2.innerHTML = '<span style="font-size:1.1rem">➕</span><span>New folder…</span>';
    nb2.addEventListener('click', function () {
      var name = prompt('Folder name:');
      if (!name || !name.trim()) return;
      if (window._ufCreateFolder) window._ufCreateFolder(uid, toCourse, name.trim());
      overlay2.remove();
      onPick(toCourse, name.trim());
    });
    box2.appendChild(nb2);
    overlay2.appendChild(box2);
    document.body.appendChild(overlay2);
  }

  function showCardPicker() {
    var overlay = document.createElement('div');
    overlay.style.cssText =
      'position:fixed;inset:0;background:rgba(0,0,0,.6);display:flex;align-items:center;justify-content:center;z-index:10001;';
    overlay.addEventListener('click', function (e) {
      if (e.target === overlay) overlay.remove();
    });
    var box = document.createElement('div');
    box.style.cssText =
      'background:var(--dp-solid);border:1px solid rgba(255,255,255,.12);border-radius:18px;padding:22px 20px;max-width:340px;width:90%;max-height:75vh;overflow-y:auto;display:flex;flex-direction:column;gap:8px;';
    var hdr = document.createElement('div');
    hdr.style.cssText = 'font-weight:800;font-size:.95rem;color:var(--on-glass);margin-bottom:2px;';
    hdr.textContent = 'Move to…';
    box.appendChild(hdr);
    var sub = document.createElement('div');
    sub.style.cssText = 'font-size:.78rem;color:var(--on-glass-faint);margin-bottom:6px;';
    sub.textContent = 'Pick a destination card';
    box.appendChild(sub);
    var glSkillNames = window._glSkillNames || {};
    Object.keys(glSkillNames).forEach(function (sk) {
      var c = { id: 'german-' + sk, short: 'german-' + sk, name: 'German ' + glSkillNames[sk] };
      var isCurrent = c.id === fromCourse.id;
      var b = document.createElement('button');
      b.style.cssText =
        'display:flex;align-items:center;gap:10px;background:' +
        (isCurrent ? 'rgba(155,93,229,.18)' : 'rgba(255,255,255,.06)') +
        ';border:1px solid ' +
        (isCurrent ? 'rgba(155,93,229,.4)' : 'rgba(255,255,255,.1)') +
        ';border-radius:12px;padding:10px 14px;cursor:pointer;color:var(--on-glass);font-family:Nunito,sans-serif;font-size:.85rem;font-weight:700;text-align:left;width:100%;transition:background .13s;';
      b.innerHTML =
        '<span style="font-size:1.1rem">📚</span><span style="flex:1">' +
        glSkillNames[sk] +
        (isCurrent ? ' (current)' : '') +
        '</span>';
      b.addEventListener('mouseenter', function () {
        b.style.background = 'rgba(155,93,229,.25)';
      });
      b.addEventListener('mouseleave', function () {
        b.style.background = isCurrent ? 'rgba(155,93,229,.18)' : 'rgba(255,255,255,.06)';
      });
      b.addEventListener('click', function () {
        overlay.remove();
        showFolderPicker(c);
      });
      box.appendChild(b);
    });
    var cancel = document.createElement('button');
    cancel.style.cssText =
      'margin-top:6px;background:transparent;border:none;color:rgba(255,255,255,.35);font-family:Nunito,sans-serif;font-size:.8rem;font-weight:700;cursor:pointer;padding:6px;border-radius:8px;transition:color .13s;';
    cancel.textContent = 'Cancel';
    cancel.addEventListener('mouseenter', function () {
      cancel.style.color = 'rgba(255,255,255,.6)';
    });
    cancel.addEventListener('mouseleave', function () {
      cancel.style.color = 'rgba(255,255,255,.35)';
    });
    cancel.addEventListener('click', function () {
      overlay.remove();
    });
    box.appendChild(cancel);
    overlay.appendChild(box);
    document.body.appendChild(overlay);
  }

  showCardPicker();
}

export async function aiExportToCourse(title, text, course, _folder) {
  if (!course) {
    window.showToast('No course', 'Open a course first');
    return;
  }
  var uid = window._currentUser && (window._currentUser.id || window._currentUser.sub);
  if (!uid) {
    window.showToast('Not logged in', 'Please sign in first');
    return;
  }
  if (_folder === undefined) {
    ufDestPicker(uid, course, function (picked) {
      aiExportToCourse(title, text, course, picked);
    });
    return;
  }
  var blob = await aiMakePdfBlob(title, text);
  if (!blob) return;
  var fname =
    title
      .slice(0, 50)
      .replace(/[^\w\s-]/g, '')
      .trim() + '.pdf';
  var file = new File([blob], fname, { type: 'application/pdf' });
  try {
    await window._ufUpload(uid, course, file, null, _folder || null);
    var dest = _folder
      ? '"' + _folder + '" in ' + (course.name || course.short)
      : course.name || course.short;
    window.showToast('Exported ✓', fname + ' added to ' + dest);
  } catch (e) {
    window.showToast('Export failed', e.message);
  }
}

export function aiShowExportModal(title, text) {
  var modal = document.getElementById('aiExportModal');
  var list = document.getElementById('aiExportCourseList');
  var status = document.getElementById('aiExportStatus');
  if (!modal) return;
  status.textContent = '';
  list.innerHTML = '';

  var allCourses = [];
  Object.values(window.SEMS || {}).forEach(function (sem) {
    (sem.courses || []).forEach(function (c) {
      allCourses.push(c);
    });
  });

  if (!allCourses.length) {
    list.innerHTML =
      '<p style="color:var(--on-glass-muted);font-size:.85rem">No courses found.</p>';
  } else {
    allCourses.forEach(function (course) {
      var btn = document.createElement('button');
      btn.style.cssText =
        'display:flex;align-items:center;gap:10px;background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.1);border-radius:12px;padding:10px 14px;cursor:pointer;color:var(--on-glass);font-family:Nunito,sans-serif;font-size:.85rem;font-weight:700;text-align:left;transition:background .13s;width:100%';
      btn.innerHTML =
        '<span style="font-size:1.1rem">📚</span><span style="flex:1">' +
        (course.name || course.short) +
        '</span>';
      btn.addEventListener('mouseenter', function () {
        this.style.background = 'rgba(155,93,229,.2)';
      });
      btn.addEventListener('mouseleave', function () {
        this.style.background = 'rgba(255,255,255,.06)';
      });
      btn.addEventListener('click', function () {
        btn.disabled = true;
        var uid = window._currentUser && (window._currentUser.id || window._currentUser.sub);
        if (!uid) {
          status.textContent = '⚠️ Not signed in';
          return;
        }
        modal.style.display = 'none';
        ufDestPicker(uid, course, async function (folder) {
          modal.style.display = 'flex';
          status.textContent = '⏳ Uploading…';
          await aiExportToCourse(title, text, course, folder);
          status.textContent = '✓ Done!';
          setTimeout(function () {
            modal.style.display = 'none';
            status.textContent = '';
          }, 1200);
        });
      });
      list.appendChild(btn);
    });
  }

  modal.style.display = 'flex';
}

export function aiResponseActions(rawText, context) {
  var title = '';
  var headingMatch = rawText.match(/^#{1,3} (.+)/m);
  if (headingMatch) {
    title = headingMatch[1].trim();
  } else {
    var firstLine = rawText
      .replace(/^[\s\n]+/, '')
      .split('\n')[0]
      .replace(/\*\*/g, '')
      .trim();
    title = firstLine.length > 60 ? firstLine.slice(0, 60) + '…' : firstLine;
  }
  if (!title) title = 'AI Response';

  var bar = document.createElement('div');
  bar.className = 'ai-action-bar';

  var dlBtn = document.createElement('button');
  dlBtn.className = 'ai-action-btn';
  dlBtn.innerHTML =
    '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg> Download PDF';
  dlBtn.addEventListener('click', function () {
    aiDownloadPdf(title, rawText);
  });

  var expBtn = document.createElement('button');
  expBtn.className = 'ai-action-btn';
  expBtn.innerHTML =
    '<svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/><line x1="12" y1="11" x2="12" y2="17"/><line x1="9" y1="14" x2="15" y2="14"/></svg> Export to course';
  expBtn.addEventListener('click', function () {
    if (context === 'panel') {
      aiExportToCourse(title, rawText, window.activeCourseRef);
    } else {
      aiShowExportModal(title, rawText);
    }
  });

  bar.appendChild(dlBtn);
  bar.appendChild(expBtn);
  return bar;
}
